DROP TABLE IF EXISTS DbEndpoint;
DROP TABLE IF EXISTS DbEntry;


CREATE TABLE DbEndpoint (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    KeyName TEXT NOT NULL UNIQUE,
    Host TEXT NOT NULL,
    Port INTEGER NOT NULL DEFAULT -1,              
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP, 
    State INTEGER DEFAULT 0
);

CREATE TABLE DbEntry (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  EndpointKey TEXT NOT NULL,
  KeyName TEXT NOT NULL,
  ConnectionString TEXT NOT NULL,
  CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP, 
  IsMonitoring BOOLEAN DEFAULT 0,
  UNIQUE(EndpointKey, KeyName),
  FOREIGN KEY(EndpointKey) REFERENCES DbEndpoint(KeyName)
);

