DROP TABLE IF EXISTS DbEndpoint;


CREATE TABLE DbEndpoint (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    EndpointKey TEXT NOT NULL UNIQUE,
    Host TEXT NOT NULL,
    Port INTEGER NOT NULL DEFAULT -1,              
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP, 
    State INTEGER DEFAULT 0
);

CREATE TABLE DbEntry (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  EndpointId INTEGER NOT NULL,
  EntryKey TEXT NOT NULL,
  UserName TEXT NOT NULL,
  Password TEXT NOT NULL,
  CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP, 
  IsMonitoring BOOLEAN DEFAULT 0,
  FOREIGN KEY(EndpointId) REFERENCES DbEndpoint(Id)
);

