BEGIN TRANSACTION;

DROP TABLE IF EXISTS DbEntry;
DROP TABLE IF EXISTS MonitorChange;
DROP TABLE IF EXISTS MonitorTask;
DROP TABLE IF EXISTS DbEndpoint;

CREATE TABLE DbEndpoint (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    KeyName TEXT NOT NULL UNIQUE,
    Host TEXT NOT NULL,
    Port INTEGER NOT NULL DEFAULT -1,              
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP, 
    State INTEGER DEFAULT 0
);

CREATE TABLE DbEntry (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  EndpointKey TEXT NOT NULL,
  KeyName TEXT NOT NULL,
  ConnectionString TEXT NOT NULL,
  CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP, 
  IsMonitoring BOOLEAN DEFAULT 0,
  UNIQUE(EndpointKey, KeyName),
  FOREIGN KEY(EndpointKey) REFERENCES DbEndpoint(KeyName)
);

CREATE TABLE MonitorTask (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  TaskName TEXT NOT NULL,
  EndpointKey TEXT NOT NULL,
  TaskState INTEGER NOT NULL DEFAULT 0, -- 0: Ready; 1:OnGoing; 2:Concluding; 3:Completed
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
  UNIQUE(EndpointKey, TaskName),
  FOREIGN KEY(EndpointKey) REFERENCES DbEndpoint(KeyName)
);

CREATE TABLE MonitorChange (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  TaskID INTEGER NOT NULL,
  Content TEXT NOT NULL,
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
  FOREIGN KEY(TaskID) REFERENCES MonitorTask(Id)
);

COMMIT;

